### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by bigpocho** [zyndagj/BSMAPz#14]
hello im following the installation instructions
already clone de git 
did the make bsmapz
and when running the test i got the following:
(BIT) pocho@DESKTOP-8JA094T:~/git-repos/BSMAPz$ sudo make test
OK - converted test_data/test_paired.sam to sorted and indexed BAM
Makefile:70: recipe for target 'test_data/test_paired.sam.bam.mr' failed
make: *** [test_data/test_paired.sam.bam.mr] Error 1

i have samtools installed:
(BIT) pocho@DESKTOP-8JA094T:~/git-repos/BSMAPz$ which samtools
/home/pocho/anaconda3/envs/BIT/bin/samtools
(BIT) pocho@DESKTOP-8JA094T:~/git-repos/BSMAPz$ samtools --version
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.

any idea what to do about this? thanks in advance

**Comment by zyndagj** [comment]
Can you share your
- operating system `lsb_release -a`
- python version `python --version`

I have not done rigorous testing with python3, so that could be the problem. The packages I uploaded to conda have been tested, so you may have luck there.

https://anaconda.org/zyndagj/bsmapz

Also, you generally don't want to run `make test` with `sudo` since files may be created (and require `sudo rm` afterward) and your environment could change.

**Comment by bigpocho** [comment]
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
$ python --version
Python 3.7.5

thank you for tip about make test, i will try with the conda link now

**Comment by bigpocho** [comment]
it worked when i created a new enviroment with python 2.7 ty
